version: '3'

services: 
    api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: nodejs
        command: npm run start:dev
        ports:
            - "3010:3000"
        volumes: 
            - .:/home/api/
            - ./node_modules:/home/api/node_modules
        networks: 
            - application
        depends_on:
            - db
        
    db:
        image: mongo:latest
        env_file: 
            - .env
        restart: always       
        ports:
        - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: lucas
            MONGO_INITDB_ROOT_PASSWORD: 123
            MONGO_INITDB_DATABASE: pizz_finder_api

        volumes:
        - mongodb_data_container:/data/db
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        networks: 
            - application
networks:
    application:
        driver: bridge
volumes: 
    mongodb_data_container: