apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-deployment
    labels:
        app: api
spec:
    replicas: 2
    selector:
        matchLabels:
            app: api
    template:
        metadata:
            labels:
                app: api
                tier: backend
        spec:
         containers:
         - name: api
           image: lpmezuraro/api_pizz
           imagePullPolicy: Never
           env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATABASE_HOST
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATABASE_USER
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATABASE_PASS
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: PORT
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATABASE_NAME  
           ports:
           - containerPort: 3000
         volumes:
         - name: secret-volume
           secret:
            secretName: app-secret
