apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  PORT: '3000'
  DATABASE_PORT: '27017'
  DATABASE_HOST: 'mongodb'
  DATABASE_USER: lucas
  DATABASE_PASS: '123'
  DATABASE_NAME: 'pizz_finder_api'

