apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  MONGODB_INITDB_DATABASE: 'pizz_finder_api'
  MONGODB_INITDB_ROOT_USERNAME: 'lucas'
  MONGODB_INITDB_ROOT_PASSWORD: '123'

