apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-container
          image: mongo:latest
          imagePullPolicy: Never  
          ports:
          - containerPort: 27017
          env:
            - name: MONGODB_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MONGODB_INITDB_DATABASE
            - name: MONGODB_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MONGODB_INITDB_ROOT_USERNAME
            - name: MONGODB_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MONGODB_INITDB_ROOT_PASSWORD
          volumeMounts:
          - name: mongodb-persistent-storage
            mountPath: /data/db
          - name: mongo-initdb
            mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim2
      - name: mongo-initdb
        configMap:
          name: mongo-initdb